### ISSUE TITLE
Add support for link text field (title/label)

### ISSUE THREAD

**Issue by Henkisch** [winteragency/sanity-plugin-link-field#1]
Add support for link text

- String field
- Not required, but used ahead of internal link titles/urls if it's set

**Comment by marcusforsberg** [comment]
@Henkisch Just pushed this in v1.1.0, please give it a try and see if it works as expected.

```ts
// ...
export default defineConfig({
  //...
  plugins: [
    linkField({
      enableText: true,
      textLabel: 'Custom text label' // Optional, defaults to "Text"
    }),
  ],
})
```

**Comment by marcusforsberg** [comment]
@Henkisch This was just pushed in v1.1.0 👍 

```ts
defineField({
  name: 'link',
  title: 'Link',
  type: 'link',
  options: {
    enableText: true,
    textLabel: 'Custom label' // Optional label for the field, defaults to "Text" 
  }
})
```

**Comment by Henkisch** [comment]
> @Henkisch This was just pushed in v1.1.0 👍
> 
> ```ts
> defineField({
>   name: 'link',
>   title: 'Link',
>   type: 'link',
>   options: {
>     enableText: true,
>     textLabel: 'Custom label' // Optional label for the field, defaults to "Text" 
>   }
> })
> ```

🎉 👏
