### ISSUE TITLE
Add ability have default values/selections 

### ISSUE THREAD

**Issue by brentrobbins** [winteragency/sanity-plugin-link-field#17]
I would love if we could set default values/selections. For example:

- New window checked by default
- External URL selected as the link type by default, or any of the other available types other than the current internal link

**Comment by marcusforsberg** [comment]
This should already be possible using the normal `initialValue` property on the field:

```ts
defineField({
  name: 'link',
  type: 'link',
  initialValue: {
    type: 'external',
    url: 'https://google.com/search',
    blank: true,
    parameters: '?q=sanity'
  }
})
```

<img width="573" alt="Screenshot 2024-08-06 at 08 41 56" src="https://github.com/user-attachments/assets/98cc75bc-1db0-47da-8a40-6fbd7e1e3447">

Please feel free to re-open this if that doesn't work for you.
