### ISSUE TITLE
Sanity Studio Crashes When Inputting Text in Link Field Before Selecting Link

### ISSUE THREAD

**Issue by mariusfredriks1** [winteragency/sanity-plugin-link-field#8]
Intermittent Studio Crash When Editing Link Field with `enableText` Option

Hello,

I've encountered an issue with the `sanity-plugin-link-field` in my Sanity Studio, which causes the studio to crash when I try to interact with a link field configured with `enableText: true`.

**Steps to Reproduce:**
1. Add a link field to the schema with the following configuration:

```
defineField({
     name: 'link',
     title: 'Link',
     type: 'link',
     options: {
       enableText: true,
       textLabel: 'Link Text',
     }
   })
```

2. Open the document in Sanity Studio.
3. Attempt to write in the text field for the link **before** setting a URL or internal reference.

**Expected Behavior:**
The text input should be usable without the studio crashing, regardless of whether a URL or internal reference has been set.

**Actual Behavior:**
The studio crashes with the following error:
```
Error: Cannot read properties of undefined (reading 'options')
at CustomLinkInput (webpack-internal:///(app-pages-browser)/./node_modules/sanity-plugin-link-field/dist/index.mjs:1184:22)
```
**Workaround:**
Temporarily removing `enableText` and then re-adding it seems to reinitialize the component state and prevents the crash when reattempting the above steps.

**Environment:**
- Sanity Studio version: 3.31.0
- sanity-plugin-link-field version: 1.1.1
- Browser: [Chrome/124.0.6367.91]
- OS: [Windows/11]

Has anyone else experienced similar issues or does anyone have insights on why this might be happening? Any help or guidance would be greatly appreciated!

Thank you!

**Comment by marcusforsberg** [comment]
Hey @mariusfredriks1, thanks for opening this and sorry for the hassle. Version v1.1.2 should fix this!
